AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  DataLocation:
    Type: String
    Default: s3://ol.pyfive.com/data/orig.json
    Description: Data source
Resources:
  BeerPlaces:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: python3.6
      Handler: lambda_function.lambda_handler
      Policies: AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          PATH_MAP: '{"/": "DATA_ON_S3"}'
          DATA_ON_S3: !Ref DataLocation
      Events:
        GetScores:
          Type: Api
          Properties:
            Path: /
            Method: get
